const DB_KEY='nexo2_db_v1';
const seed={
  settings:{businessName:'Mi negocio',owner:'',currency:'S/',theme:'light'},
  customers:[
    {id:'c1',name:'Juan Pérez',phone:'999111222',note:'Vecino',createdAt:Date.now()-86400000*40},
    {id:'c2',name:'Rosa Quispe',phone:'988222333',note:'',createdAt:Date.now()-86400000*20}
  ],
  debts:[
    {id:'d1',customerId:'c1',amount:28.5,description:'Arroz, leche y gaseosa',date:today(-6),dueDate:today(-1),status:'open'},
    {id:'d2',customerId:'c2',amount:14,description:'Productos varios',date:today(-2),dueDate:today(5),status:'open'}
  ],
  payments:[{id:'p1',customerId:'c1',amount:10,date:today(-2),note:'Abono'}],
  products:[
    {id:'pr1',name:'Gaseosa 500 ml',code:'775000100001',price:3.5,cost:2.4,stock:24,minStock:6},
    {id:'pr2',name:'Arroz 1 kg',code:'775000100002',price:5.2,cost:4.1,stock:12,minStock:5},
    {id:'pr3',name:'Leche evaporada',code:'775000100003',price:4.2,cost:3.35,stock:4,minStock:6}
  ],
  sales:[
    {id:'s1',date:today(0),total:18.4,cost:13.1,payment:'Yape',items:[{productId:'pr1',name:'Gaseosa 500 ml',qty:2,price:3.5},{productId:'pr2',name:'Arroz 1 kg',qty:1,price:5.2},{productId:'pr3',name:'Leche evaporada',qty:1,price:4.2}]},
    {id:'s2',date:today(-1),total:36.5,cost:26.2,payment:'Efectivo',items:[]}
  ],
  expenses:[{id:'e1',date:today(0),amount:8,description:'Movilidad'}],
  cashClosures:[]
};
function today(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
let db=load();let route='home';let cart=[];let deferredPrompt=null;let stream=null;
const view=document.querySelector('#view'),title=document.querySelector('#pageTitle'),modal=document.querySelector('#modal'),modalContent=document.querySelector('#modalContent'),toastEl=document.querySelector('#toast');
function load(){try{return JSON.parse(localStorage.getItem(DB_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db));document.querySelector('#businessNameMini').textContent=(db.settings.businessName||'NEXO NEGOCIO').toUpperCase()}
const money=n=>`${db.settings.currency||'S/'} ${Number(n||0).toFixed(2)}`;
const uid=p=>p+Math.random().toString(36).slice(2,9);
const byDate=(arr,date=today())=>arr.filter(x=>x.date===date);
function customer(id){return db.customers.find(c=>c.id===id)}
function debtBalance(customerId){const d=db.debts.filter(x=>x.customerId===customerId&&x.status==='open').reduce((a,b)=>a+b.amount,0);const p=db.payments.filter(x=>x.customerId===customerId).reduce((a,b)=>a+b.amount,0);return Math.max(0,d-p)}
function totalDebt(){return db.customers.reduce((a,c)=>a+debtBalance(c.id),0)}
function salesToday(){return byDate(db.sales).reduce((a,b)=>a+b.total,0)}
function profitToday(){return byDate(db.sales).reduce((a,b)=>a+(b.total-b.cost),0)-byDate(db.expenses).reduce((a,b)=>a+b.amount,0)}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
function setRoute(r){route=r;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render()}
function render(){save();const names={home:'Inicio',debts:'Fiados',sales:'Ventas',products:'Productos',more:'Más'};title.textContent=names[route]||'NEXO';view.innerHTML=({home:homeView,debts:debtsView,sales:salesView,products:productsView,more:moreView}[route]||homeView)();bindView()}
function homeView(){const low=db.products.filter(p=>p.stock<=p.minStock).length;const sales=byDate(db.sales);return `
<section class="hero"><div class="hero-row"><div><p>Ventas de hoy</p><h2>${money(salesToday())}</h2><p>${sales.length} movimientos registrados</p></div><span class="pill">● En línea</span></div></section>
<div class="grid grid-2 desktop-4 stats">
  <div class="card stat"><small>Ganancia estimada</small><b>${money(profitToday())}</b></div>
  <div class="card stat"><small>Total por cobrar</small><b>${money(totalDebt())}</b></div>
  <div class="card stat"><small>Clientes con deuda</small><b>${db.customers.filter(c=>debtBalance(c.id)>0).length}</b></div>
  <div class="card stat"><small>Stock bajo</small><b>${low}</b></div>
</div>
<div class="section-head"><h2>¿Qué quieres hacer?</h2></div>
<div class="quick-actions">
<button data-action="new-sale"><span>🛒</span>Vender</button><button data-action="new-debt"><span>💰</span>Registrar fiado</button><button data-action="new-payment"><span>💵</span>Registrar pago</button><button data-action="new-product"><span>📦</span>Ingresar producto</button>
</div>
<div class="section-head"><h2>Actividad reciente</h2><button class="link-btn" data-route-jump="sales">Ver todo</button></div>
${recentActivity()}`}
function recentActivity(){const rows=[...db.sales.map(x=>({type:'Venta',date:x.date,amount:x.total,icon:'🛒'})),...db.debts.map(x=>({type:'Fiado',date:x.date,amount:x.amount,icon:'💰'})),...db.payments.map(x=>({type:'Pago recibido',date:x.date,amount:x.amount,icon:'💵'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);if(!rows.length)return '<div class="empty">Aún no hay movimientos.</div>';return `<div class="list">${rows.map(r=>`<div class="list-item"><div class="avatar">${r.icon}</div><div class="list-main"><b>${r.type}</b><span>${r.date}</span></div><div class="amount">${money(r.amount)}</div></div>`).join('')}</div>`}
function debtsView(){const q='';return `<div class="kpi-row"><div class="kpi-chip"><small>Total por cobrar</small><b>${money(totalDebt())}</b></div><div class="kpi-chip"><small>Clientes activos</small><b>${db.customers.filter(c=>debtBalance(c.id)>0).length}</b></div><div class="kpi-chip"><small>Vencidos</small><b>${db.debts.filter(d=>d.status==='open'&&d.dueDate&&d.dueDate<today()).length}</b></div></div>
<div class="section-head"><h2>Clientes</h2><button class="link-btn" data-action="new-debt">+ Fiado</button></div>
<div class="searchbar"><input id="customerSearch" placeholder="Buscar cliente..." value="${q}"><button class="secondary" data-action="new-customer">＋</button></div><div id="customerList">${customerList('')}</div>`}
function customerList(q){const rows=db.customers.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>debtBalance(b.id)-debtBalance(a.id));if(!rows.length)return '<div class="empty">No encontramos clientes.</div>';return `<div class="list">${rows.map(c=>{const bal=debtBalance(c.id);return `<button class="list-item" data-customer="${c.id}" style="width:100%;text-align:left;color:inherit"><div class="avatar">${c.name.slice(0,2).toUpperCase()}</div><div class="list-main"><b>${c.name}</b><span>${c.phone||'Sin teléfono'}</span></div><div class="amount">${money(bal)}<small>${bal?'Pendiente':'Al día'}</small></div></button>`}).join('')}</div>`}
function salesView(){const total7=lastDays(7).reduce((a,d)=>a+db.sales.filter(s=>s.date===d.date).reduce((x,y)=>x+y.total,0),0);return `<div class="grid grid-2"><div class="card stat"><small>Hoy</small><b>${money(salesToday())}</b></div><div class="card stat"><small>Últimos 7 días</small><b>${money(total7)}</b></div></div><div class="section-head"><h2>Últimos 7 días</h2><button class="link-btn" data-action="new-sale">+ Venta</button></div><div class="card"><div class="chart">${salesBars()}</div></div><div class="section-head"><h2>Historial</h2></div>${salesList()}`}
function lastDays(n){return Array.from({length:n},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(n-1-i));return{date:d.toISOString().slice(0,10),label:d.toLocaleDateString('es-PE',{weekday:'short'}).slice(0,2)}})}
function salesBars(){const vals=lastDays(7).map(d=>({...d,total:db.sales.filter(s=>s.date===d.date).reduce((a,b)=>a+b.total,0)}));const max=Math.max(...vals.map(x=>x.total),1);return vals.map(x=>`<div class="bar" style="height:${Math.max(8,x.total/max*100)}%" title="${money(x.total)}"><span>${x.label}</span></div>`).join('')}
function salesList(){const rows=[...db.sales].sort((a,b)=>b.date.localeCompare(a.date));if(!rows.length)return '<div class="empty">Todavía no hay ventas.</div>';return `<div class="list">${rows.map(s=>`<div class="list-item"><div class="avatar">🧾</div><div class="list-main"><b>Venta ${s.id.slice(-5).toUpperCase()}</b><span>${s.date} · ${s.payment}</span></div><div class="amount">${money(s.total)}<small>Gan. ${money(s.total-s.cost)}</small></div></div>`).join('')}</div>`}
function productsView(){const low=db.products.filter(p=>p.stock<=p.minStock).length;return `<div class="grid grid-2"><div class="card stat"><small>Productos</small><b>${db.products.length}</b></div><div class="card stat"><small>Stock bajo</small><b>${low}</b></div></div><div class="section-head"><h2>Inventario</h2><button class="link-btn" data-action="scan-product">Escanear</button></div><div class="searchbar"><input id="productSearch" placeholder="Nombre o código"><button class="secondary" data-action="new-product">＋</button></div><div id="productList">${productList('')}</div>`}
function productList(q){const rows=db.products.filter(p=>(p.name+' '+p.code).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));if(!rows.length)return '<div class="empty">No hay productos registrados.</div>';return `<div class="list">${rows.map(p=>`<button class="list-item" data-product="${p.id}" style="width:100%;text-align:left;color:inherit"><div class="avatar">📦</div><div class="list-main"><b>${p.name}</b><span>${p.code||'Sin código'} · ${money(p.price)}</span></div><div class="amount">${p.stock}<small>${p.stock<=p.minStock?'Stock bajo':'unidades'}</small></div></button>`).join('')}</div>`}
function moreView(){return `<div class="list"><button class="list-item" data-more="reports"><div class="avatar">📊</div><div class="list-main"><b>Reportes</b><span>Ventas, ganancias y gastos</span></div><b>›</b></button><button class="list-item" data-more="expenses"><div class="avatar">🧾</div><div class="list-main"><b>Gastos</b><span>Registra salidas de dinero</span></div><b>›</b></button><button class="list-item" data-more="settings"><div class="avatar">⚙️</div><div class="list-main"><b>Configuración</b><span>Negocio, respaldo y apariencia</span></div><b>›</b></button><button class="list-item" data-more="about"><div class="avatar">N2</div><div class="list-main"><b>NEXO 2.0</b><span>PWA local · versión 2.0.0</span></div><b>›</b></button></div>`}
function bindView(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-route-jump]').forEach(b=>b.onclick=()=>setRoute(b.dataset.routeJump));document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>showCustomer(b.dataset.customer));document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>editProduct(b.dataset.product));document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>showMore(b.dataset.more));const cs=document.querySelector('#customerSearch');if(cs)cs.oninput=e=>document.querySelector('#customerList').innerHTML=customerList(e.target.value);const ps=document.querySelector('#productSearch');if(ps)ps.oninput=e=>document.querySelector('#productList').innerHTML=productList(e.target.value)}
function openModal(html){modalContent.innerHTML=`<div class="modal-card">${html}</div>`;modal.showModal();modalContent.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}function closeModal(){stopScanner();modal.close()}
function modalHead(t){return `<div class="modal-head"><h2>${t}</h2><button class="close-btn" data-close>×</button></div>`}
function action(a){document.querySelector('#actionSheet')?.close();({
 'new-sale':newSale,'new-debt':newDebt,'new-payment':newPayment,'new-customer':newCustomer,'new-product':()=>editProduct(),
 'new-expense':newExpense,'close-day':closeDay,'scan-product':scanProduct
}[a]||(()=>{}))()}
function newCustomer(){openModal(`${modalHead('Nuevo cliente')}<form id="customerForm"><div class="field"><label>Nombre</label><input name="name" required autofocus></div><div class="field"><label>Celular</label><input name="phone" inputmode="tel"></div><div class="field"><label>Nota</label><input name="note"></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`);document.querySelector('#customerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.customers.push({id:uid('c'),name:f.get('name').trim(),phone:f.get('phone').trim(),note:f.get('note').trim(),createdAt:Date.now()});save();closeModal();render();toast('Cliente creado')}}
function newDebt(){if(!db.customers.length)return newCustomer();openModal(`${modalHead('Registrar fiado')}<form id="debtForm"><div class="field"><label>Cliente</label><select name="customerId">${db.customers.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>Monto</label><input name="amount" type="number" min="0.1" step="0.1" required inputmode="decimal"></div><div class="field"><label>Detalle</label><textarea name="description" placeholder="Ej. arroz, leche, gaseosa"></textarea></div><div class="field"><label>Fecha de pago prometida</label><input name="dueDate" type="date"></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Guardar fiado</button></div></form>`);document.querySelector('#debtForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.debts.push({id:uid('d'),customerId:f.get('customerId'),amount:+f.get('amount'),description:f.get('description').trim()||'Fiado',date:today(),dueDate:f.get('dueDate'),status:'open'});save();closeModal();render();toast('Fiado registrado')}}
function newPayment(prefill=''){const owing=db.customers.filter(c=>debtBalance(c.id)>0);if(!owing.length)return toast('No hay deudas pendientes');openModal(`${modalHead('Registrar pago')}<form id="payForm"><div class="field"><label>Cliente</label><select name="customerId">${owing.map(c=>`<option value="${c.id}" ${c.id===prefill?'selected':''}>${c.name} · ${money(debtBalance(c.id))}</option>`).join('')}</select></div><div class="field"><label>Monto recibido</label><input name="amount" type="number" min="0.1" step="0.1" required></div><div class="field"><label>Nota</label><input name="note" placeholder="Efectivo, Yape..."></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Registrar pago</button></div></form>`);document.querySelector('#payForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),cid=f.get('customerId'),amt=Math.min(+f.get('amount'),debtBalance(cid));db.payments.push({id:uid('p'),customerId:cid,amount:amt,date:today(),note:f.get('note').trim()});save();closeModal();render();toast('Pago registrado')}}
function showCustomer(id){const c=customer(id),bal=debtBalance(id),mov=[...db.debts.filter(x=>x.customerId===id).map(x=>({date:x.date,label:x.description,amount:x.amount,type:'debt'})),...db.payments.filter(x=>x.customerId===id).map(x=>({date:x.date,label:x.note||'Pago',amount:x.amount,type:'pay'}))].sort((a,b)=>b.date.localeCompare(a.date));openModal(`${modalHead(c.name)}<div class="hero"><p>Saldo pendiente</p><h2>${money(bal)}</h2><p>${c.phone||'Sin teléfono registrado'}</p></div><div class="form-actions"><button class="secondary" id="waBtn">WhatsApp</button><button class="primary" id="payBtn">Registrar pago</button></div><div class="section-head"><h2>Historial</h2></div><div class="list">${mov.map(m=>`<div class="list-item"><div class="avatar">${m.type==='pay'?'↓':'↑'}</div><div class="list-main"><b>${m.label}</b><span>${m.date}</span></div><div class="amount">${m.type==='pay'?'-':'+'}${money(m.amount)}</div></div>`).join('')||'<div class="empty">Sin movimientos.</div>'}</div>`);document.querySelector('#payBtn').onclick=()=>{closeModal();newPayment(id)};document.querySelector('#waBtn').onclick=()=>{const text=`Hola ${c.name}, te recordamos que tienes un saldo pendiente de ${money(bal)} en ${db.settings.businessName}. Gracias.`;window.open(`https://wa.me/${(c.phone||'').replace(/\D/g,'')}?text=${encodeURIComponent(text)}`,'_blank')}}
function editProduct(id=''){const p=db.products.find(x=>x.id===id)||{name:'',code:'',price:'',cost:'',stock:0,minStock:5};openModal(`${modalHead(id?'Editar producto':'Nuevo producto')}<form id="productForm"><div class="field"><label>Nombre</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Código de barras</label><div class="searchbar"><input name="code" value="${esc(p.code)}"><button type="button" class="secondary" id="scanInside">Escanear</button></div></div><div class="grid grid-2"><div class="field"><label>Precio venta</label><input name="price" type="number" step="0.1" value="${p.price}" required></div><div class="field"><label>Costo</label><input name="cost" type="number" step="0.1" value="${p.cost}" required></div><div class="field"><label>Stock</label><input name="stock" type="number" step="1" value="${p.stock}" required></div><div class="field"><label>Stock mínimo</label><input name="minStock" type="number" step="1" value="${p.minStock}" required></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Guardar</button></div>${id?'<button type="button" class="danger-btn" id="deleteProduct" style="width:100%;margin-top:10px">Eliminar producto</button>':''}</form>`);document.querySelector('#productForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),obj={id:id||uid('pr'),name:f.get('name').trim(),code:f.get('code').trim(),price:+f.get('price'),cost:+f.get('cost'),stock:+f.get('stock'),minStock:+f.get('minStock')};if(id)db.products=db.products.map(x=>x.id===id?obj:x);else db.products.push(obj);save();closeModal();render();toast('Producto guardado')};document.querySelector('#scanInside').onclick=()=>scanInto(document.querySelector('[name="code"]'));if(id)document.querySelector('#deleteProduct').onclick=()=>{if(confirm('¿Eliminar este producto?')){db.products=db.products.filter(x=>x.id!==id);save();closeModal();render()}}}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function newSale(){cart=[];renderSaleModal()}
function renderSaleModal(){const total=cart.reduce((a,i)=>a+i.price*i.qty,0);openModal(`${modalHead('Nueva venta')}<div class="searchbar"><input id="saleSearch" placeholder="Buscar o escanear producto"><button class="secondary" id="saleScan">▣</button></div><div id="saleResults">${saleProductResults('')}</div><div class="section-head"><h2>Carrito</h2><b>${money(total)}</b></div><div class="list" id="cartList">${cartHtml()}</div><form id="saleForm"><div class="field"><label>Método de pago</label><select name="payment"><option>Efectivo</option><option>Yape</option><option>Plin</option><option>Transferencia</option><option>Fiado</option></select></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary" ${cart.length?'':'disabled'}>Cobrar ${money(total)}</button></div></form>`);const ss=document.querySelector('#saleSearch');ss.oninput=e=>document.querySelector('#saleResults').innerHTML=saleProductResults(e.target.value);document.querySelector('#saleResults').onclick=e=>{const b=e.target.closest('[data-add-product]');if(!b)return;addCart(b.dataset.addProduct)};document.querySelector('#cartList').onclick=e=>{const b=e.target.closest('[data-cart]');if(!b)return;changeCart(b.dataset.cart,b.dataset.dir)};document.querySelector('#saleScan').onclick=()=>scanInto(ss,code=>{ss.value=code;document.querySelector('#saleResults').innerHTML=saleProductResults(code)});document.querySelector('#saleForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),payment=f.get('payment'),total=cart.reduce((a,i)=>a+i.price*i.qty,0),cost=cart.reduce((a,i)=>a+i.cost*i.qty,0);if(payment==='Fiado'){closeModal();newDebtFromCart(total);return}for(const i of cart){const p=db.products.find(x=>x.id===i.productId);p.stock-=i.qty}db.sales.push({id:uid('s'),date:today(),total,cost,payment,items:cart});save();closeModal();render();toast('Venta registrada')}}
function saleProductResults(q){const rows=db.products.filter(p=>p.stock>0&&(p.name+' '+p.code).toLowerCase().includes(q.toLowerCase())).slice(0,5);return `<div class="list">${rows.map(p=>`<button class="list-item" data-add-product="${p.id}" style="width:100%;text-align:left;color:inherit"><div class="avatar">＋</div><div class="list-main"><b>${p.name}</b><span>Stock ${p.stock} · ${p.code}</span></div><div class="amount">${money(p.price)}</div></button>`).join('')||'<div class="empty">Sin coincidencias.</div>'}</div>`}
function addCart(id){const p=db.products.find(x=>x.id===id),it=cart.find(x=>x.productId===id);if(it){if(it.qty>=p.stock)return toast('Stock insuficiente');it.qty++}else cart.push({productId:p.id,name:p.name,qty:1,price:p.price,cost:p.cost});renderSaleModal()}
function changeCart(id,dir){const i=cart.find(x=>x.productId===id),p=db.products.find(x=>x.id===id);if(dir==='plus'&&i.qty<p.stock)i.qty++;if(dir==='minus')i.qty--;cart=cart.filter(x=>x.qty>0);renderSaleModal()}
function cartHtml(){if(!cart.length)return '<div class="empty">Agrega productos a la venta.</div>';return cart.map(i=>`<div class="list-item"><div class="list-main"><b>${i.name}</b><span>${money(i.price)} c/u</span></div><button class="icon-btn" data-cart="${i.productId}" data-dir="minus">−</button><b>${i.qty}</b><button class="icon-btn" data-cart="${i.productId}" data-dir="plus">＋</button></div>`).join('')}
function newDebtFromCart(total){openModal(`${modalHead('Venta fiada')}<form id="debtCart"><div class="field"><label>Cliente</label><select name="customerId">${db.customers.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>Total</label><input value="${total.toFixed(2)}" disabled></div><div class="field"><label>Fecha prometida</label><input name="dueDate" type="date"></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Confirmar</button></div></form>`);document.querySelector('#debtCart').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);for(const i of cart){db.products.find(x=>x.id===i.productId).stock-=i.qty}db.sales.push({id:uid('s'),date:today(),total,cost:cart.reduce((a,i)=>a+i.cost*i.qty,0),payment:'Fiado',items:cart});db.debts.push({id:uid('d'),customerId:f.get('customerId'),amount:total,description:'Venta fiada',date:today(),dueDate:f.get('dueDate'),status:'open'});save();closeModal();render();toast('Venta fiada registrada')}}
function newExpense(){openModal(`${modalHead('Registrar gasto')}<form id="expenseForm"><div class="field"><label>Monto</label><input name="amount" type="number" step="0.1" min="0.1" required></div><div class="field"><label>Descripción</label><input name="description" required></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`);document.querySelector('#expenseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.expenses.push({id:uid('e'),date:today(),amount:+f.get('amount'),description:f.get('description').trim()});save();closeModal();render();toast('Gasto registrado')}}
function closeDay(){const data={id:uid('cc'),date:today(),sales:salesToday(),profit:profitToday(),debts:byDate(db.debts).reduce((a,b)=>a+b.amount,0),closedAt:new Date().toISOString()};db.cashClosures.push(data);save();toast('Caja cerrada y guardada')}
function showMore(type){if(type==='reports'){const month=today().slice(0,7),sales=db.sales.filter(s=>s.date.startsWith(month)).reduce((a,b)=>a+b.total,0),profit=db.sales.filter(s=>s.date.startsWith(month)).reduce((a,b)=>a+b.total-b.cost,0)-db.expenses.filter(e=>e.date.startsWith(month)).reduce((a,b)=>a+b.amount,0);openModal(`${modalHead('Reportes')}<div class="grid grid-2"><div class="card stat"><small>Ventas del mes</small><b>${money(sales)}</b></div><div class="card stat"><small>Ganancia estimada</small><b>${money(profit)}</b></div><div class="card stat"><small>Por cobrar</small><b>${money(totalDebt())}</b></div><div class="card stat"><small>Gastos del mes</small><b>${money(db.expenses.filter(e=>e.date.startsWith(month)).reduce((a,b)=>a+b.amount,0))}</b></div></div>`)}
if(type==='expenses')openModal(`${modalHead('Gastos')}<button class="primary" data-action="new-expense" style="width:100%;margin-bottom:12px">+ Registrar gasto</button><div class="list">${[...db.expenses].reverse().map(e=>`<div class="list-item"><div class="avatar">🧾</div><div class="list-main"><b>${e.description}</b><span>${e.date}</span></div><div class="amount">-${money(e.amount)}</div></div>`).join('')||'<div class="empty">Sin gastos.</div>'}</div>`),bindModalActions();
if(type==='settings')settingsModal();if(type==='about')openModal(`${modalHead('Acerca de')}<div class="hero"><p>NEXO NEGOCIO</p><h2>Versión 2.0.0</h2><p>Ventas, fiados, inventario y caja desde el celular.</p></div><p class="muted">Esta versión guarda la información en el dispositivo. Está preparada para evolucionar a sincronización en la nube y suscripciones.</p>`)}
function bindModalActions(){modalContent.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{closeModal();action(b.dataset.action)})}
function settingsModal(){openModal(`${modalHead('Configuración')}<form id="settingsForm"><div class="field"><label>Nombre del negocio</label><input name="businessName" value="${esc(db.settings.businessName)}"></div><div class="field"><label>Propietario</label><input name="owner" value="${esc(db.settings.owner)}"></div><div class="form-actions"><button type="button" class="secondary" id="exportBtn">Exportar respaldo</button><button class="primary">Guardar</button></div><button type="button" class="danger-btn" id="resetBtn" style="width:100%;margin-top:10px">Restablecer demo</button></form>`);document.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.settings.businessName=f.get('businessName').trim()||'Mi negocio';db.settings.owner=f.get('owner').trim();save();closeModal();render();toast('Configuración guardada')};document.querySelector('#exportBtn').onclick=exportBackup;document.querySelector('#resetBtn').onclick=()=>{if(confirm('¿Restablecer todos los datos de demostración?')){db=structuredClone(seed);save();closeModal();render()}}}
function exportBackup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nexo-respaldo-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function scanProduct(){openModal(`${modalHead('Escanear código')}<div class="scanner-box"><video id="scannerVideo" playsinline muted></video><div class="scanner-frame"></div></div><p class="muted">Apunta al código de barras. Si tu navegador no admite detección automática, puedes escribirlo manualmente.</p><div class="field"><label>Código manual</label><input id="manualCode"></div><button class="primary" id="useManual" style="width:100%">Usar código</button>`);const input=document.querySelector('#manualCode');document.querySelector('#useManual').onclick=()=>{const code=input.value.trim();if(!code)return;closeModal();const p=db.products.find(x=>x.code===code);p?editProduct(p.id):editProductWithCode(code)};startScanner(code=>{closeModal();const p=db.products.find(x=>x.code===code);p?editProduct(p.id):editProductWithCode(code)})}
function editProductWithCode(code){editProduct();setTimeout(()=>{const el=document.querySelector('[name="code"]');if(el)el.value=code},0)}
function scanInto(input,cb){openModal(`${modalHead('Escanear')}<div class="scanner-box"><video id="scannerVideo" playsinline muted></video><div class="scanner-frame"></div></div><p class="muted">Apunta al código.</p><div class="field"><label>Código manual</label><input id="manualCode"></div><button class="primary" id="useManual" style="width:100%">Usar código</button>`);const done=code=>{input.value=code;closeModal();cb?.(code)};document.querySelector('#useManual').onclick=()=>done(document.querySelector('#manualCode').value.trim());startScanner(done)}
async function startScanner(onCode){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});const video=document.querySelector('#scannerVideo');video.srcObject=stream;await video.play();if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39','qr_code']});let running=true;const loop=async()=>{if(!running||!video.isConnected)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){running=false;navigator.vibrate?.(80);onCode(codes[0].rawValue);return}}catch{}requestAnimationFrame(loop)};loop()}else toast('Escaneo automático no compatible; usa el código manual.')}catch(e){toast('No se pudo abrir la cámara') }}
function stopScanner(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));document.querySelector('#fab').onclick=()=>document.querySelector('#actionSheet').showModal();document.querySelector('#actionSheet').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelector('#themeBtn').onclick=()=>{db.settings.theme=db.settings.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=db.settings.theme;save()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').hidden=false});document.querySelector('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.querySelector('#installBtn').hidden=true}};document.documentElement.dataset.theme=db.settings.theme||'light';save();render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
